AWSTemplateFormatVersion: '2010-09-09'
Description: MSK Serverless cluster with IAM auth

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id
  SubnetC:
    Type: AWS::EC2::Subnet::Id
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  ClusterName:
    Type: String
    Default: msk-serverless-demo

Resources:
  MskServerlessCluster:
    Type: AWS::MSK::ServerlessCluster
    Properties:
      ClusterName: !Ref ClusterName
      VpcConfigs:
        - SubnetIds:
            - !Ref SubnetA
            - !Ref SubnetB
            - !Ref SubnetC
          SecurityGroups:
            - !Ref SecurityGroupId
      ClientAuthentication:
        Sasl:
          Iam:
            Enabled: true

Outputs:
  ClusterArn:
    Value: !Ref MskServerlessCluster
    Export:
      Name: !Sub "${AWS::StackName}-ClusterArn"
